// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct PingPongStackProgram;

impl sails_rs::client::Program for PingPongStackProgram {}

pub trait PingPongStack {
    type Env: sails_rs::client::GearEnv;
    fn ping_pong_stack(
        &self,
    ) -> sails_rs::client::Service<ping_pong_stack::PingPongStackImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> PingPongStack
    for sails_rs::client::Actor<PingPongStackProgram, E>
{
    type Env = E;
    fn ping_pong_stack(
        &self,
    ) -> sails_rs::client::Service<ping_pong_stack::PingPongStackImpl, Self::Env> {
        self.service(stringify!(PingPongStack))
    }
}

pub trait PingPongStackCtors {
    type Env: sails_rs::client::GearEnv;
    fn create_ping(
        self,
        code_id: CodeId,
    ) -> sails_rs::client::PendingCtor<PingPongStackProgram, io::CreatePing, Self::Env>;
    fn create_pong(
        self,
    ) -> sails_rs::client::PendingCtor<PingPongStackProgram, io::CreatePong, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> PingPongStackCtors
    for sails_rs::client::Deployment<PingPongStackProgram, E>
{
    type Env = E;
    fn create_ping(
        self,
        code_id: CodeId,
    ) -> sails_rs::client::PendingCtor<PingPongStackProgram, io::CreatePing, Self::Env> {
        self.pending_ctor((code_id,))
    }
    fn create_pong(
        self,
    ) -> sails_rs::client::PendingCtor<PingPongStackProgram, io::CreatePong, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(CreatePing (code_id: CodeId) -> ());
    sails_rs::io_struct_impl!(CreatePong () -> ());
}

pub mod ping_pong_stack {
    use super::*;

    pub trait PingPongStack {
        type Env: sails_rs::client::GearEnv;
        fn start(&mut self, limit: u32) -> sails_rs::client::PendingCall<io::Start, Self::Env>;
        fn ping(&mut self, countdown: u32) -> sails_rs::client::PendingCall<io::Ping, Self::Env>;
    }

    pub struct PingPongStackImpl;

    impl<E: sails_rs::client::GearEnv> PingPongStack
        for sails_rs::client::Service<PingPongStackImpl, E>
    {
        type Env = E;
        fn start(&mut self, limit: u32) -> sails_rs::client::PendingCall<io::Start, Self::Env> {
            self.pending_call((limit,))
        }
        fn ping(&mut self, countdown: u32) -> sails_rs::client::PendingCall<io::Ping, Self::Env> {
            self.pending_call((countdown,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Start (limit: u32) -> ());
        sails_rs::io_struct_impl!(Ping (countdown: u32) -> ());
    }
}
