// Code generated by sails-client-gen-v2. DO NOT EDIT.
#[allow(unused_imports)]
use sails::{client::*, collections::*, prelude::*};
pub struct PingPongStackProgram;

impl PingPongStackProgram {
    pub const ROUTE_ID_PING_PONG_STACK: u8 = 1;
}

impl sails::client::Program for PingPongStackProgram {}

pub trait PingPongStack {
    type Env: sails::client::GearEnv;
    fn ping_pong_stack(
        &self,
    ) -> sails::client::Service<ping_pong_stack::PingPongStackImpl, Self::Env>;
}

impl<E: sails::client::GearEnv> PingPongStack
    for sails::client::Actor<PingPongStackProgram, E>
{
    type Env = E;
    fn ping_pong_stack(
        &self,
    ) -> sails::client::Service<ping_pong_stack::PingPongStackImpl, Self::Env> {
        self.service(PingPongStackProgram::ROUTE_ID_PING_PONG_STACK)
    }
}
pub trait PingPongStackCtors {
    type Env: sails::client::GearEnv + sails::client::EnvWithCtor;
    fn create_ping(
        self,
        code_id: CodeId,
    ) -> sails::client::PendingCtor<PingPongStackProgram, io::CreatePing, Self::Env>;
    fn create_pong(
        self,
    ) -> sails::client::PendingCtor<PingPongStackProgram, io::CreatePong, Self::Env>;
}

impl<E: sails::client::GearEnv + sails::client::EnvWithCtor> PingPongStackCtors
    for sails::client::Deployment<PingPongStackProgram, E>
{
    type Env = E;
    fn create_ping(
        self,
        code_id: CodeId,
    ) -> sails::client::PendingCtor<PingPongStackProgram, io::CreatePing, Self::Env> {
        self.pending_ctor((code_id,))
    }
    fn create_pong(
        self,
    ) -> sails::client::PendingCtor<PingPongStackProgram, io::CreatePong, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails::io_struct_impl!(CreatePing (code_id: CodeId) -> (), 0);
    sails::io_struct_impl!(CreatePong () -> (), 1);
}

pub mod ping_pong_stack {
    use super::*;

    pub trait PingPongStack {
        type Env: sails::client::GearEnv;
        fn ping(&mut self, countdown: u32) -> sails::client::PendingCall<io::Ping, Self::Env>;
        fn start(&mut self, limit: u32) -> sails::client::PendingCall<io::Start, Self::Env>;
    }

    pub struct PingPongStackImpl;

    impl sails::client::Identifiable for PingPongStackImpl {
        const INTERFACE_ID: sails::InterfaceId =
            sails::InterfaceId::from_bytes_8([48, 181, 231, 61, 179, 133, 133, 236]);
    }

    impl<E: sails::client::GearEnv> PingPongStack
        for sails::client::Service<PingPongStackImpl, E>
    {
        type Env = E;
        fn ping(&mut self, countdown: u32) -> sails::client::PendingCall<io::Ping, Self::Env> {
            self.pending_call((countdown,))
        }
        fn start(&mut self, limit: u32) -> sails::client::PendingCall<io::Start, Self::Env> {
            self.pending_call((limit,))
        }
    }

    pub mod io {
        use super::*;
        sails::io_struct_impl!(Ping (countdown: u32) -> (), 0, <super::PingPongStackImpl as sails::client::Identifiable>::INTERFACE_ID);
        sails::io_struct_impl!(Start (limit: u32) -> (), 1, <super::PingPongStackImpl as sails::client::Identifiable>::INTERFACE_ID);
    }
}
