// Code generated by sails-client-gen from this-that.json. DO NOT EDIT.
#![automatically_derived]
#![allow(unused)]
use parity_scale_codec::{Decode, Encode};
use sails_client::{Call, Sender};
pub type Alias = u32;
pub type OptionAlias = Option<u8>;
pub type ResultAlias = Result<u8, string>;
pub type VecAlias = Vec<u8>;
#[derive(PartialEq, Debug, Encode, Decode)]
pub struct ThisThatSvcAppTupleStruct(bool);
#[derive(PartialEq, Debug, Encode, Decode)]
pub struct ThisThatSvcAppDoThatParam {
    p1: u32,
    p2: String,
    p3: ThisThatSvcAppManyVariants,
}
#[derive(PartialEq, Debug, Encode, Decode)]
pub enum ThisThatSvcAppManyVariants {
    One,
    Two(u32),
    Three(Option<u32>),
    Four { a: u32, b: Option<u16> },
    Five((String, u32)),
    Six((u32)),
}

#[doc(hidden)]
#[derive(PartialEq, Debug, Encode, Decode)]
pub struct DoThisRequestArgs {
    p1: u32,
    p2: String,
    p3: (Option<String>, u8),
    p4: ThisThatSvcAppTupleStruct,
}

#[doc(hidden)]
#[derive(PartialEq, Debug, Encode, Decode)]
pub struct DoThatRequestArgs {
    param: ThisThatSvcAppDoThatParam,
}

#[doc(hidden)]
#[derive(PartialEq, Debug, Encode, Decode)]
pub struct ThisRequestArgs {}

#[doc(hidden)]
#[derive(PartialEq, Debug, Encode, Decode)]
pub struct ThatRequestArgs {}

#[derive(Default, Clone)]
pub struct Client {
    program_id: [u8; 32],
}

impl Client {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn with_program_id(mut self, program_id: impl Into<[u8; 32]>) -> Self {
        self.program_id = program_id.into();
        self
    }

    pub fn do_this(
        &self,
        p1: u32,
        p2: String,
        p3: (Option<String>, u8),
        p4: ThisThatSvcAppTupleStruct,
    ) -> Call<(String, u32)> {
        let mut payload = Vec::from("DoThis/");
        DoThisRequestArgs { p1, p2, p3, p4 }.encode_to(&mut payload);

        Call::new(payload).with_program_id(self.program_id)
    }
    pub fn do_that(
        &self,
        param: ThisThatSvcAppDoThatParam,
    ) -> Call<Result<(String, u32), (String)>> {
        let mut payload = Vec::from("DoThat/");
        DoThatRequestArgs { param }.encode_to(&mut payload);

        Call::new(payload).with_program_id(self.program_id)
    }
    pub fn this(&self) -> Call<u32> {
        let mut payload = Vec::from("This/");
        ThisRequestArgs {}.encode_to(&mut payload);

        Call::new(payload).with_program_id(self.program_id)
    }
    pub fn that(&self) -> Call<Result<String, String>> {
        let mut payload = Vec::from("That/");
        ThatRequestArgs {}.encode_to(&mut payload);

        Call::new(payload).with_program_id(self.program_id)
    }
}
