// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct RedirectProxyClientProgram;
impl sails_rs::client::Program for RedirectProxyClientProgram {}
pub trait RedirectProxyClient {
    type Env: sails_rs::client::GearEnv;
    fn proxy(&self) -> sails_rs::client::Service<proxy::ProxyImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> RedirectProxyClient
    for sails_rs::client::Actor<RedirectProxyClientProgram, E>
{
    type Env = E;
    fn proxy(&self) -> sails_rs::client::Service<proxy::ProxyImpl, Self::Env> {
        self.service_at(
            sails_rs::InterfaceId::from_bytes_8([115, 132, 52, 118, 255, 19, 124, 126]),
            1,
        )
    }
}
pub trait RedirectProxyClientCtors {
    type Env: sails_rs::client::GearEnv;
    /// Proxy Program's constructor
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
        target: ActorId,
    ) -> sails_rs::client::PendingCtor<RedirectProxyClientProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> RedirectProxyClientCtors
    for sails_rs::client::Deployment<RedirectProxyClientProgram, E>
{
    type Env = E;
    fn new(
        self,
        target: ActorId,
    ) -> sails_rs::client::PendingCtor<RedirectProxyClientProgram, io::New, Self::Env> {
        self.pending_ctor((target,))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (target: ActorId) -> (), 0);
}

pub mod proxy {
    use super::*;
    pub trait Proxy {
        type Env: sails_rs::client::GearEnv;
        /// Get program ID of the target program via client
        fn get_program_id(&self) -> sails_rs::client::PendingCall<io::GetProgramId, Self::Env>;
    }
    pub struct ProxyImpl;
    impl<E: sails_rs::client::GearEnv> Proxy for sails_rs::client::Service<ProxyImpl, E> {
        type Env = E;
        fn get_program_id(&self) -> sails_rs::client::PendingCall<io::GetProgramId, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(GetProgramId () -> ActorId, 0);
    }
}
