[workspace]
members = ["cargo:rs/cli"]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.32.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
    # macOS
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    # Linux (glibc)
    "aarch64-unknown-linux-gnu",
    "x86_64-unknown-linux-gnu",
    # Linux (musl)
    "aarch64-unknown-linux-musl",
    "x86_64-unknown-linux-musl",
    # Windows
    "aarch64-pc-windows-msvc",
    "x86_64-pc-windows-msvc",
    # Android
    "aarch64-linux-android",
    "x86_64-linux-android",
]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false
# Whether to consider the binaries in a package for distribution (defaults true)
dist = false
# Build only the required packages, and individually
precise-builds = true
# Specify which packages should be distributed
packages = ["sails-cli"]
# Which actions to run on pull requests
pr-run-mode = "plan"
# Whether dist should create a Github Release or use an existing draft
create-release = false
# Skip checking whether the specified configuration files are up to date
allow-dirty = ["ci"]
# Whether +crt-static should be used on msvc
msvc-crt-static = true
# Additional configuration of CI backends for Android targets
github-build-setup = "../build-setup.yml"

# Custom runners for GitHub Actions
# To build Android targets, we need to use x86_64 runners, as Android NDK is not installed on aarch64 runners
[dist.github-custom-runners.aarch64-linux-android]
runner = "ubuntu-22.04"
host = "x86_64-unknown-linux-gnu"
