program PingPongStack {
    constructors {
        CreatePing(code_id: CodeId);
        CreatePong();
    }
    services {
        PingPongStack,
    }
}

service PingPongStack {
    functions {
        Start(limit: u32) -> ();
        Ping(countdown: u32) -> ();
    }
}