[package]
name = "{{ client-project-name }}"
version = "0.1.0"
edition = "2024"

[dependencies]
mockall = { version = "{{ mockall-version }}", optional = true }
sails-rs = "{{ sails-rs-version }}"

[build-dependencies]
{{ project-name }} = { path = ".." }
sails-client-gen = "{{ sails-rs-version }}"
sails-idl-gen = "{{ sails-rs-version }}"

[features]
{{ mocks-feature-name }} = ["sails-rs/mockall", "dep:mockall"]
