// Code generated by sails-sol-client-gen. DO NOT EDIT.
use sails_rs::{
    ActorId,
    client::{GearEnv, Identifiable, MethodMeta, PendingCall, PendingCtor, ServiceCall},
    solidity,
};

#[derive(Debug, Clone)]
pub struct IEthappClient<E: GearEnv> {
    env: E,
    program_id: ActorId,
}

impl<E: GearEnv> IEthappClient<E> {
    pub fn new(env: E, program_id: ActorId) -> Self {
        Self { env, program_id }
    }

    pub fn with_program_id(mut self, program_id: ActorId) -> Self {
        self.program_id = program_id;
        self
    }

    pub fn program_id(&self) -> ActorId {
        self.program_id
    }

    pub fn env(&self) -> &E {
        &self.env
    }
}
pub struct CreatePayable;

impl Identifiable for CreatePayable {
    const INTERFACE_ID: sails_rs::InterfaceId = sails_rs::InterfaceId::zero();
}

impl MethodMeta for CreatePayable {
    const ENTRY_ID: u16 = 0;
}

impl ServiceCall for CreatePayable {
    type Params = sails_rs::prelude::Vec<u8>;
    type Reply = sails_rs::prelude::Vec<u8>;

    fn encode_params_with_header(
        _route_idx: u8,
        value: &Self::Params,
    ) -> sails_rs::prelude::Vec<u8> {
        let selector = solidity::selector("createPayable(bool)");
        [selector.as_slice(), value.as_slice()].concat()
    }

    fn decode_reply_with_header(
        _route_idx: u8,
        payload: impl AsRef<[u8]>,
    ) -> Result<Self::Reply, sails_rs::scale_codec::Error> {
        Ok(payload.as_ref().to_vec())
    }
}

impl<E: GearEnv> IEthappClient<E> {
    pub const CREATE_PAYABLE_SIGNATURE: &'static str = "createPayable(bool)";

    pub fn create_payable(&self, encoded_args: impl AsRef<[u8]>) -> PendingCall<CreatePayable, E> {
        PendingCall::<CreatePayable, E>::new(
            self.env.clone(),
            self.program_id,
            0,
            encoded_args.as_ref().to_vec(),
        )
    }
}
pub struct CreatePrg;

impl Identifiable for CreatePrg {
    const INTERFACE_ID: sails_rs::InterfaceId = sails_rs::InterfaceId::zero();
}

impl MethodMeta for CreatePrg {
    const ENTRY_ID: u16 = 1;
}

impl ServiceCall for CreatePrg {
    type Params = sails_rs::prelude::Vec<u8>;
    type Reply = sails_rs::prelude::Vec<u8>;

    fn encode_params_with_header(
        _route_idx: u8,
        value: &Self::Params,
    ) -> sails_rs::prelude::Vec<u8> {
        let selector = solidity::selector("createPrg(bool)");
        [selector.as_slice(), value.as_slice()].concat()
    }

    fn decode_reply_with_header(
        _route_idx: u8,
        payload: impl AsRef<[u8]>,
    ) -> Result<Self::Reply, sails_rs::scale_codec::Error> {
        Ok(payload.as_ref().to_vec())
    }
}

impl<E: GearEnv> IEthappClient<E> {
    pub const CREATE_PRG_SIGNATURE: &'static str = "createPrg(bool)";

    pub fn create_prg(&self, encoded_args: impl AsRef<[u8]>) -> PendingCall<CreatePrg, E> {
        PendingCall::<CreatePrg, E>::new(
            self.env.clone(),
            self.program_id,
            0,
            encoded_args.as_ref().to_vec(),
        )
    }
}
pub struct Svc1DoThis;

impl Identifiable for Svc1DoThis {
    const INTERFACE_ID: sails_rs::InterfaceId = sails_rs::InterfaceId::zero();
}

impl MethodMeta for Svc1DoThis {
    const ENTRY_ID: u16 = 2;
}

impl ServiceCall for Svc1DoThis {
    type Params = sails_rs::prelude::Vec<u8>;
    type Reply = sails_rs::prelude::Vec<u8>;

    fn encode_params_with_header(
        _route_idx: u8,
        value: &Self::Params,
    ) -> sails_rs::prelude::Vec<u8> {
        let selector = solidity::selector("svc1DoThis(bool,uint32,string)");
        [selector.as_slice(), value.as_slice()].concat()
    }

    fn decode_reply_with_header(
        _route_idx: u8,
        payload: impl AsRef<[u8]>,
    ) -> Result<Self::Reply, sails_rs::scale_codec::Error> {
        Ok(payload.as_ref().to_vec())
    }
}

impl<E: GearEnv> IEthappClient<E> {
    pub const SVC_1_DO_THIS_SIGNATURE: &'static str = "svc1DoThis(bool,uint32,string)";

    pub fn svc_1_do_this(&self, encoded_args: impl AsRef<[u8]>) -> PendingCall<Svc1DoThis, E> {
        PendingCall::<Svc1DoThis, E>::new(
            self.env.clone(),
            self.program_id,
            0,
            encoded_args.as_ref().to_vec(),
        )
    }
}
pub struct Svc1DoThisPayable;

impl Identifiable for Svc1DoThisPayable {
    const INTERFACE_ID: sails_rs::InterfaceId = sails_rs::InterfaceId::zero();
}

impl MethodMeta for Svc1DoThisPayable {
    const ENTRY_ID: u16 = 3;
}

impl ServiceCall for Svc1DoThisPayable {
    type Params = sails_rs::prelude::Vec<u8>;
    type Reply = sails_rs::prelude::Vec<u8>;

    fn encode_params_with_header(
        _route_idx: u8,
        value: &Self::Params,
    ) -> sails_rs::prelude::Vec<u8> {
        let selector = solidity::selector("svc1DoThisPayable(bool,uint32)");
        [selector.as_slice(), value.as_slice()].concat()
    }

    fn decode_reply_with_header(
        _route_idx: u8,
        payload: impl AsRef<[u8]>,
    ) -> Result<Self::Reply, sails_rs::scale_codec::Error> {
        Ok(payload.as_ref().to_vec())
    }
}

impl<E: GearEnv> IEthappClient<E> {
    pub const SVC_1_DO_THIS_PAYABLE_SIGNATURE: &'static str = "svc1DoThisPayable(bool,uint32)";

    pub fn svc_1_do_this_payable(
        &self,
        encoded_args: impl AsRef<[u8]>,
    ) -> PendingCall<Svc1DoThisPayable, E> {
        PendingCall::<Svc1DoThisPayable, E>::new(
            self.env.clone(),
            self.program_id,
            0,
            encoded_args.as_ref().to_vec(),
        )
    }
}
pub struct Svc1This;

impl Identifiable for Svc1This {
    const INTERFACE_ID: sails_rs::InterfaceId = sails_rs::InterfaceId::zero();
}

impl MethodMeta for Svc1This {
    const ENTRY_ID: u16 = 4;
}

impl ServiceCall for Svc1This {
    type Params = sails_rs::prelude::Vec<u8>;
    type Reply = sails_rs::prelude::Vec<u8>;

    fn encode_params_with_header(
        _route_idx: u8,
        value: &Self::Params,
    ) -> sails_rs::prelude::Vec<u8> {
        let selector = solidity::selector("svc1This(bool,address)");
        [selector.as_slice(), value.as_slice()].concat()
    }

    fn decode_reply_with_header(
        _route_idx: u8,
        payload: impl AsRef<[u8]>,
    ) -> Result<Self::Reply, sails_rs::scale_codec::Error> {
        Ok(payload.as_ref().to_vec())
    }
}

impl<E: GearEnv> IEthappClient<E> {
    pub const SVC_1_THIS_SIGNATURE: &'static str = "svc1This(bool,address)";

    pub fn svc_1_this(&self, encoded_args: impl AsRef<[u8]>) -> PendingCall<Svc1This, E> {
        PendingCall::<Svc1This, E>::new(
            self.env.clone(),
            self.program_id,
            0,
            encoded_args.as_ref().to_vec(),
        )
    }
}
