service ServiceWithEvents {
    functions {
        DoThis(p1: U256, p2: MyParam) -> U64;
    }

    events {
        One(u64),
        Two { id: u8, reference: u64 },
        Three(MyParam),
        Reset,
    }

    types {
        struct MyParam {
            f1: U256,
            f2: [u8],
            f3: Option<(U64, U256)>,
        }
    }
}