service Service { // Anonymous service becomes named "Service" for the test
    functions {
        DoThis(p1: u32, p2: MyParam) -> u16;
        DoThat(p1: (u8, u32)) -> u8;
    }
    types {
        struct MyParam {
            f1: u32,
            f2: [string],
            f3: Option<(u8, u32)>,
        }

        enum MyParam2 {
            Variant1,
            Variant2(u32),
            Variant3(u32),
            Variant4(u8, u32),
            Variant5 { f1: string, f2: [u8] },
        }
    }
}