constructor {
  New : ();
};

service Redirect {
  /// !@interface_id32 = 0xfd852dad
  /// !@interface_uid64 = 0x01e35eb7fd852dad
  /// Exit from program with inheritor ID
  /// !@entry_id = 0x0001
  Exit : (inheritor_id: actor_id) -> null;
  /// Returns program ID of the current program
  /// !@entry_id = 0x0002
  query GetProgramId : () -> actor_id;
};

