
!@sails: 0.9.2

service Redirect {
    functions {
        /// Exit from program with inheritor ID
        Exit(inheritor_id: ActorId);
        /// Returns program ID of the current program
        @query
        GetProgramId() -> ActorId;
    }
}

program ProgramToDo {
    constructors {
        New();
    }
    services {
        Redirect,
    }
}
