!@sails: 0.10.2

@partial
service PartialIdlService@0x6f9649495e041ebc {
    events {
        @entry-id: 2
        ThirdDone(String);
    }
    functions {
        @entry-id: 1
        Second(val: u32) -> u32;
        @entry-id: 2
        Third() -> String;
    }
}

program PartialIdlClient {
    constructors {
        New();
    }
    services {
        PartialIdlService@0x6f9649495e041ebc,
    }
}
