[package]
name = "counter"
version = "0.1.0"
edition = "2021"

[dependencies]
gstd.workspace = true
sails-rtl.workspace = true
counter-app = { path = "../app" }

[build-dependencies]
gwasm-builder.workspace = true
sails-client-gen.workspace = true
sails-idl-gen.workspace = true
counter-app = { path = "../app" }

[dev-dependencies]
gtest.workspace = true
sails-rtl.workspace = true
parity-scale-codec = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["rt", "macros"] }
