[package]
name = "this-that-svc-invoke-example"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gclient.workspace = true
sails-client.workspace = true
parity-scale-codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
gtest = { workspace = true }
tokio = { version = "1.23.0", features = ["full"] }