[package]
name = "sails-rtl-gstd"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hex.workspace = true
gstd.workspace = true
sails-rtl.workspace = true
