[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
demo-app = { path = "../app" }

[build-dependencies]
demo-app = { path = "../app" }
gwasm-builder.workspace = true
sails-idl-gen.workspace = true

[dev-dependencies]
futures.workspace = true
gclient.workspace = true
gtest.workspace = true
demo-client = { path = "../client" }
sails.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }
