[package]
name = "no-svcs-prog"
version = "0.1.0"
edition.workspace = true

[dependencies]
no-svcs-prog-app = { path = "../app" }
sails-rs.workspace = true

[build-dependencies]
no-svcs-prog-app = { path = "../app" }
sails-rs = { workspace = true, features = ["build", "wasm-builder"] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
sails-rs = { workspace = true, features = ["gtest"] }
