[package]
name = "no-svcs-prog"
version = "0.1.0"
edition = "2021"

[dependencies]
prog-without-svcs-app = { path = "../app" }
sails-macros.workspace = true
sails-rtl.workspace = true

[build-dependencies]
gwasm-builder.workspace = true
prog-without-svcs-app = { path = "../app" }
sails-idl-gen.workspace = true
