[package]
name = "{{ project-name }}"
version = "0.1.0"
edition = "2021"

[dependencies]
sails-rs = "{{sails-rs-version}}"

[build-dependencies]
sails-rs = { version = "{{sails-rs-version}}", features = ["wasm-builder"] }
