[workspace]
{% if with-client %}
members = ["client"]
{% endif %}

[package]
name = "{{ project-name }}"
version = "0.1.0"
edition = "2021"

[dependencies]
{{ app-project-name }} = { path = "app" }

[build-dependencies]
{{ app-project-name }} = { path = "app" }
sails-rs = { version = "{{ sails-rs-version }}", features = ["wasm-builder"] }
sails-idl-gen = "{{ sails-rs-version }}"
{% if with-client and with-gtest %}
[dev-dependencies]
{{ project-name }} = { path = ".", features = ["wasm-binary"] }
{{ client-project-name }} = { path = "client" }
sails-rs = { version = "{{ sails-rs-version }}", features = ["gtest"] }
tokio = { version = "{{ tokio-version }}", features = ["rt", "macros"] }
{% endif %}
[features]
wasm-binary = []
