[package]
name = "redirect-proxy-client"
version = "0.1.0"
edition.workspace = true

[dependencies]
sails-rs.workspace = true

[build-dependencies]
redirect-proxy = { path = "../proxy" }
sails-client-gen.workspace = true
sails-rs = { workspace = true, features = ["idl-gen"] }
