constructor {
  /// Proxy Program's constructor
  New : (target: actor_id);
};

service Proxy {
  /// !@interface_id = 0x4c9c43383a64063a
  /// Get program ID of the target program via client
  /// !@entry_id = 0x0001
  query GetProgramId : () -> actor_id;
};

