program Proxy {
    constructors {
        /// Proxy Program's constructor
        New(target: ActorId);
    }
    services {
        Proxy,
    }
}

service Proxy {
    functions {
        /// Get program ID of the target program via client
        @query
        GetProgramId() -> ActorId;
    }
}