
!@sails: 0.10.2

service Proxy@0x73843476ff137c7e {
    functions {
        /// Get program ID of the target program via client
        @query
        GetProgramId() -> ActorId;
    }
}

program RedirectProxyClient {
    constructors {
        /// Proxy Program's constructor
        New(target: ActorId);
    }
    services {
        Proxy@0x73843476ff137c7e,
    }
}
