[package]
name = "ethapp"
version = "0.1.0"
edition = "2021"

[dependencies]
sails-rs = { workspace = true, features = ["ethexe"] }

[build-dependencies]
sails-rs = { workspace = true, features = ["ethexe", "wasm-builder"] }

[dev-dependencies]
gclient.workspace = true
gstd.workspace = true
gtest.workspace = true
sails-rs = { workspace = true, features = ["ethexe", "gtest"] }
tokio = { workspace = true, features = ["rt", "macros"] }
