// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Sails.ClientGenerator
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "sails_net_client_gen";



        /// <summary>
        ///  # Safety
        ///
        ///  Function [`free_c_string`] should be called after this function
        /// </summary>
        [DllImport(__DllName, EntryPoint = "generate_dotnet_client", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* generate_dotnet_client(byte* program_utf8, int program_len, byte* service_name_utf8, int service_name_len);

        /// <summary>
        ///  # Safety
        ///
        ///  This function should not be called before the [`generate_dotnet_client`]
        /// </summary>
        [DllImport(__DllName, EntryPoint = "free_c_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void free_c_string(byte* str);


    }



}
