[package]
name = "sails-idl-parser-v2-pest"
description = "IDL parser for the Sails framework"
documentation = "https://docs.rs/sails-idl-parser"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pest = "2"
pest_derive = "2"
anyhow = "1"
thiserror.workspace = true
