[package]
name = "sails-macros"
description = "Procedural macros for the Sails framework"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
sails-macros-core.workspace = true
proc-macro-error.workspace = true

[dev-dependencies]
parity-scale-codec = { workspace = true, features = ["derive"] }
sails.workspace = true
scale-info = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
trybuild.workspace = true
