[package]
name = "this-that-app"
version = "0.1.0"
edition = "2021"

[dependencies]
gmeta.workspace = true
gstd = { workspace = true, features = ["debug"] }
sails-macros.workspace = true
sails-service.workspace = true
parity-scale-codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
gtest = { workspace = true, optional = true }
sails-client = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }

[features]
"handlers" = []
"client" = ["dep:gtest", "dep:sails-client"]
