[package]
name = "fibonacci-stress-plain"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gstd.workspace = true
parity-scale-codec.workspace = true
fibonacci-stress-core ={ path = "../core" }

[build-dependencies]
gwasm-builder.workspace = true

[features]
std = []
default = ["std"]
