[package]
name = "event-routes"
version = "0.1.0"
edition.workspace = true

[dev-dependencies]
gtest.workspace = true
event-routes-app = { path = "app" }
sails-rs = { workspace = true, features = ["gtest", "gclient"] }
tokio = { workspace = true, features = ["rt", "macros"] }
