use crate::{
    ctor_generators::*, helpers::generate_doc_comments, mock_generator::*, service_generators::*,
    type_generators::*,
};
use convert_case::{Case, Casing};
use genco::prelude::*;
use rust::Tokens;
use sails_idl_parser_v2::ast;
use sails_idl_parser_v2::visitor::Visitor;
use std::collections::{HashMap, HashSet};

pub(crate) struct RootGenerator<'ast> {
    tokens: Tokens,
    mocks_tokens: Tokens,
    service_impl_tokens: Tokens,
    service_trait_tokens: Tokens,
    anonymous_service_name: &'ast str,
    mocks_feature_name: Option<&'ast str>,
    sails_path: &'ast str,
    external_types: HashMap<&'ast str, &'ast str>,
    no_derive_traits: bool,
    program_exported_services: Vec<&'ast str>,
    program_types: HashSet<&'ast str>,
}

impl<'ast> RootGenerator<'ast> {
    pub(crate) fn new(
        anonymous_service_name: &'ast str,
        mocks_feature_name: Option<&'ast str>,
        sails_path: &'ast str,
        external_types: HashMap<&'ast str, &'ast str>,
        no_derive_traits: bool,
    ) -> Self {
        Self {
            anonymous_service_name,
            tokens: Tokens::new(),
            mocks_tokens: Tokens::new(),
            service_impl_tokens: Tokens::new(),
            service_trait_tokens: Tokens::new(),
            mocks_feature_name,
            sails_path,
            external_types,
            no_derive_traits,
            program_exported_services: Vec::new(),
            program_types: HashSet::new(),
        }
    }

    pub(crate) fn finalize(self, with_no_std: bool) -> String {
        let mocks_tokens = if let Some(mocks_feature_name) = self.mocks_feature_name {
            quote! {
                $['\n']
                #[cfg(feature = $(quoted(mocks_feature_name)))]
                #[cfg(not(target_arch = "wasm32"))]
                extern crate std;
                $['\n']
                #[cfg(feature = $(quoted(mocks_feature_name)))]
                #[cfg(not(target_arch = "wasm32"))]
                pub mod mockall {
                    use super::*;
                    use $(self.sails_path)::mockall::*;
                    $(self.mocks_tokens)
                }
            }
        } else {
            Tokens::new()
        };

        let mut tokens = quote! {
            #[allow(unused_imports)]
            use $(self.sails_path)::{client::*, collections::*, prelude::*};
        };

        for (&name, &path) in &self.external_types {
            quote_in! { tokens =>
                #[allow(unused_imports)]
                use $path as $name;
            };
        }

        let program_name = &self.anonymous_service_name.to_case(Case::Pascal);
        quote_in! { tokens =>
            pub struct $(program_name)Program;

            impl $(self.sails_path)::client::Program for  $(program_name)Program {}

            pub trait $program_name {
                type Env: $(self.sails_path)::client::GearEnv;
                $(self.service_trait_tokens)
            }

            impl<E: $(self.sails_path)::client::GearEnv> $program_name for $(self.sails_path)::client::Actor<$(program_name)Program, E> {
                type Env = E;
                $(self.service_impl_tokens)
            }

            $(self.tokens)

            $mocks_tokens
        };

        let mut result = tokens.to_file_string().unwrap();

        if with_no_std {
            result.insert_str(
                0,
                "// Code generated by sails-client-gen. DO NOT EDIT.\n#![no_std]\n\n",
            );
        } else {
            result.insert_str(0, "// Code generated by sails-client-gen. DO NOT EDIT.\n");
        }

        result
    }
}

impl<'ast> Visitor<'ast> for RootGenerator<'ast> {
    fn visit_program_unit(&mut self, program: &'ast ast::ProgramUnit) {
        let mut ctor_gen = CtorGenerator::new(self.anonymous_service_name, self.sails_path);
        ctor_gen.visit_program_unit(program);
        self.tokens.extend(ctor_gen.finalize());

        for service_item in &program.services {
            let service_name = service_item.route.as_ref().unwrap_or(&service_item.name);
            self.program_exported_services.push(service_name);
        }

        sails_idl_parser_v2::visitor::accept_program_unit(program, self);
    }

    fn visit_service_unit(&mut self, service: &'ast ast::ServiceUnit) {
        let service_name = if service.name.is_empty() {
            self.anonymous_service_name
        } else {
            &service.name
        };

        // Generate service access methods only if the service is not exported by the program
        if !self.program_exported_services.contains(&service_name) {
            let service_name_snake = &service_name.to_case(Case::Snake);
            let service_name_pascal = &service_name.to_case(Case::Pascal);

            quote_in!(self.service_trait_tokens =>
                $['\r'] fn $(service_name_snake)(&self) -> $(self.sails_path)::client::Service<$(service_name_snake)::$(service_name_pascal)Impl, Self::Env>;
            );
            quote_in!(self.service_impl_tokens =>
                $['\r'] fn $(service_name_snake)(&self) -> $(self.sails_path)::client::Service<$(service_name_snake)::$(service_name_pascal)Impl, Self::Env> {
                    self.service(stringify!($(service_name)))
                }
            );
        }

        let mut client_gen =
            ServiceGenerator::new(service_name, self.sails_path, self.no_derive_traits);
        client_gen.visit_service_unit(service);
        self.tokens.extend(client_gen.finalize());

        let mut mock_gen = MockGenerator::new(service_name, self.sails_path);
        mock_gen.visit_service_unit(service);
        self.mocks_tokens.extend(mock_gen.finalize());
    }

    fn visit_type(&mut self, t: &'ast ast::Type) {
        self.program_types.insert(&t.name);
        if self.external_types.contains_key(t.name.as_str()) {
            return;
        }
        let mut type_gen =
            TopLevelTypeGenerator::new(&t.name, self.sails_path, self.no_derive_traits);
        type_gen.visit_type(t);
        self.tokens.extend(type_gen.finalize());
    }

    fn visit_service_expo(&mut self, service_item: &'ast ast::ServiceExpo) {
        let service_name = service_item.route.as_ref().unwrap_or(&service_item.name);
        let method_name = service_item.name.to_case(Case::Snake);
        let route_pascal_case = service_name.to_case(Case::Pascal);
        let route_snake_case = service_name.to_case(Case::Snake);

        generate_doc_comments(&mut self.service_trait_tokens, &service_item.docs);

        quote_in!(self.service_trait_tokens =>
            $['\r'] fn $(&method_name)(&self) -> $(self.sails_path)::client::Service<$(route_snake_case.clone())::$(route_pascal_case.clone())Impl, Self::Env>;
        );

        quote_in!(self.service_impl_tokens =>
            $['\r'] fn $(&method_name)(&self) -> $(self.sails_path)::client::Service<$(route_snake_case)::$(route_pascal_case)Impl, Self::Env> {
                self.service(stringify!($(service_item.name.clone())))
            }
        );
    }
}
