
!@sails: 0.10.2

service Inspector@0x75bfa84329247aeb {
    functions {
        /// Proxy call to validator.validate_nonzero(0)
        TestNonzeroPanic() throws String;
        /// Proxy call to validator.validate_range(20, 5, 15)
        TestRangePanic() -> u32 throws ValidationError;
        /// Proxy call to validator.validate_even(7)
        @query
        TestEvenPanic() -> u32 throws ();
        /// Try to deploy demo with error - should return Err
        @query
        TestFailingDemoCtor(demo_code_id: CodeId) -> ActorId throws String;
        /// Proxy call to validator.total_errors()
        @query
        TestTotalErrors() -> u32;
    }
    types {
        enum ValidationError {
            TooSmall,
            TooBig,
        }
    }
}

program InspectorClient {
    constructors {
        New(target: ActorId);
        NewWithResult(target: ActorId) throws String;
    }
    services {
        Inspector@0x75bfa84329247aeb,
    }
}
