[package]
name = "demo-client"
version = "0.1.0"
edition = "2021"

[dependencies]
mockall = { workspace = true, optional = true }
sails-rs.workspace = true

[build-dependencies]
demo = { path = "../app" }
sails-client-gen.workspace = true
sails-idl-gen.workspace = true

[features]
std = []
mockall = ["std", "sails-rs/mockall", "dep:mockall"]
