[package]
name = "demo-client"
version = "0.1.0"
edition.workspace = true

[dependencies]
mockall = { workspace = true, optional = true }
sails-rs.workspace = true

[build-dependencies]
demo = { path = "../app" }
sails-rs = { workspace = true, features = ["build"] }

[features]
with_mocks = ["sails-rs/mockall", "dep:mockall"]
