type ReferenceCount = struct {
  u32,
};

type DoThatParam = struct {
  p1: nat32,
  p2: actor_id,
  p3: ManyVariants,
};

type ManyVariants = enum {
  One,
  Two: u32,
  Three: opt u256,
  Four: struct {
    a: u32,
    b: opt u16,
  },
  Five: struct {
    str,
    h256,
  },
  Six: struct { u32 },
};

type ManyVariantsReply = enum {
  One,
  Two,
  Three,
  Four,
  Five,
  Six,
};

type TupleStruct = struct {
  bool,
};

constructor {
  /// Program constructor (called once at the very beginning of the program lifetime)
  Default : ();
  /// Another program constructor (called once at the very beginning of the program lifetime)
  New : (counter: opt u32, dog_position: opt struct { i32, i32 });
};

service PingPong {
  /// !@interface_id = 0xa5623ea9fafc5af5
  /// !@entry_id = 0x0001
  Ping : (input: str) -> result (str, str);
};

service Counter {
  /// !@interface_id = 0x89dbc2cce5b7fdcc
  /// Add a value to the counter
  /// !@entry_id = 0x0001
  Add : (value: u32) -> u32;
  /// Substract a value from the counter
  /// !@entry_id = 0x0002
  Sub : (value: u32) -> u32;
  /// Get the current value
  /// !@entry_id = 0x0003
  query Value : () -> u32;

  events {
    /// Emitted when a new value is added to the counter
    /// !@entry_id = 0x0001
    Added: u32;
    /// Emitted when a value is subtracted from the counter
    /// !@entry_id = 0x0002
    Subtracted: u32;
  }
};

service Dog {
  /// !@interface_id = 0xa76e4dbded6df3fe
  /// !@extends
  ///   MammalService (interface_id=0xadc268cf15ab73a0)
  ///   WalkerService (interface_id=0x97dcb00bd1501f98)
  /// !@entry_id = 0x0001
  MakeSound : () -> str;
  /// !@entry_id = 0x0002
  Walk : (dx: i32, dy: i32) -> null;
  /// !@entry_id = 0x0001
  query AvgWeight : () -> u32;
  /// !@entry_id = 0x0001
  query Position : () -> struct { i32, i32 };

  events {
    /// !@entry_id = 0x0001
    Barked;
    /// !@entry_id = 0x0001
    Walked: struct {
      from: struct { i32, i32 },
      to: struct { i32, i32 },
    };
  }
};

service References {
  /// !@interface_id = 0x16dec7e4480fe77c
  /// !@entry_id = 0x0001
  Add : (v: u32) -> u32;
  /// !@entry_id = 0x0002
  AddByte : (byte: u8) -> vec u8;
  /// !@entry_id = 0x0004
  GuessNum : (number: u8) -> result (str, str);
  /// !@entry_id = 0x0005
  Incr : () -> ReferenceCount;
  /// !@entry_id = 0x0008
  SetNum : (number: u8) -> result (null, str);
  /// !@entry_id = 0x0003
  query Baked : () -> str;
  /// !@entry_id = 0x0006
  query LastByte : () -> opt u8;
  /// !@entry_id = 0x0007
  query Message : () -> opt str;
};

service ThisThat {
  /// !@interface_id = 0xe7bde5a282ea98c4
  /// !@entry_id = 0x0001
  DoThat : (param: DoThatParam) -> result (struct { actor_id, nat32, ManyVariantsReply }, struct { str });
  /// !@entry_id = 0x0002
  DoThis : (p1: u32, p2: str, p3: struct { opt h160, nat8 }, p4: TupleStruct) -> struct { str, u32 };
  /// !@entry_id = 0x0003
  Noop : () -> null;
  /// !@entry_id = 0x0004
  query That : () -> result (str, str);
  /// !@entry_id = 0x0005
  query This : () -> u32;
};

service ValueFee {
  /// !@interface_id = 0x43893ea7bc6115db
  /// Return flag if fee taken and remain value,
  /// using special type `CommandReply<T>`
  /// !@entry_id = 0x0001
  DoSomethingAndTakeFee : () -> bool;

  events {
    /// !@entry_id = 0x0001
    Withheld: u128;
  }
};

service Chaos {
  /// !@interface_id = 0x8ebc6837a0fb15ce
  /// !@entry_id = 0x0001
  query PanicAfterWait : () -> null;
  /// !@entry_id = 0x0002
  query ReplyHookCounter : () -> u32;
  /// !@entry_id = 0x0003
  query TimeoutWait : () -> null;
};

