[package]
name = "this-that-svc"
version = "0.1.0"
edition = "2021"

[dependencies]
gstd.workspace = true
sails-rtl.workspace = true
this-that-svc-app = { path = "../app" }

[build-dependencies]
gwasm-builder.workspace = true
sails-idl-gen.workspace = true
this-that-svc-app = { path = "../app" }
