@partial
service Canvas@0x1234567890abcdef {
  functions {
    @entry_id: 3
    PointStatus(point: Point) -> Option<PointStatus>;
  }
  types {
    struct Point {
        x: u32,
        y: u32,
    }
    enum PointStatus {
        Active,
        Inactive,
    }
  }
}
