program MyProgram {
    constructors {
        New();
    }
    services {
        MyService: MyService
    }
}

service MyService {
    functions {
        DoSomething(p1: UnknownType) -> u32;
    }
}
