program MyProgram {
    types {
        struct ProgramType {
            val: u32,
        }
    }
    constructors { New(); }
    services { MyService: MyService }
}

service MyService {
    types {
        struct ServiceType {
            val: ProgramType, // Valid: ProgramType is defined at program level
        }
    }
    functions {
        DoSomething(p1: ProgramType) -> u32; // Valid usage
    }
}
