[package]
name = "counter-app"
version = "0.1.0"
edition = "2021"

[dependencies]
gstd = { workspace = true, features = ["debug"] }
parity-scale-codec = { workspace = true, features = ["derive"] }
sails-rtl.workspace = true
scale-info = { workspace = true, features = ["derive"] }
