[template]
sub_templates = ["program"]

[placeholders]
with-client = { type = "bool", prompt = "Add client project?" }
with-gtest = { type = "bool", prompt = "Add gtest project?" }

[hooks]
pre = ["../pre-hook.rhai"]
