[template]
sub_templates = ["program"]

[placeholders]
with-client = { type = "bool", prompt = "Add client project?", default=true }
with-gtest = { type = "bool", prompt = "Add gtest project?", default=true }

[hooks]
pre = ["../set-vars.rhai"]
