// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct InspectorClientProgram;

impl InspectorClientProgram {
    pub const ROUTE_ID_INSPECTOR: u8 = 1;
}

impl sails_rs::client::Program for InspectorClientProgram {}

pub trait InspectorClient {
    type Env: sails_rs::client::GearEnv;
    fn inspector(&self) -> sails_rs::client::Service<inspector::InspectorImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> InspectorClient
    for sails_rs::client::Actor<InspectorClientProgram, E>
{
    type Env = E;
    fn inspector(&self) -> sails_rs::client::Service<inspector::InspectorImpl, Self::Env> {
        self.service(InspectorClientProgram::ROUTE_ID_INSPECTOR)
    }
}
pub trait InspectorClientCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    #[allow(clippy::type_complexity)]
    fn new(
        self,
        target: ActorId,
    ) -> sails_rs::client::PendingCtor<
        sails_rs::client::Actor<InspectorClientProgram, Self::Env>,
        io::New,
        Self::Env,
    >;
    #[allow(clippy::type_complexity)]
    fn new_with_result(
        self,
        target: ActorId,
    ) -> sails_rs::client::PendingCtor<
        Result<sails_rs::client::Actor<InspectorClientProgram, Self::Env>, String>,
        io::NewWithResult,
        Self::Env,
    >;
}

impl<E: sails_rs::client::GearEnv> InspectorClientCtors
    for sails_rs::client::Deployment<InspectorClientProgram, E>
{
    type Env = E;
    #[allow(clippy::type_complexity)]
    fn new(
        self,
        target: ActorId,
    ) -> sails_rs::client::PendingCtor<
        sails_rs::client::Actor<InspectorClientProgram, Self::Env>,
        io::New,
        Self::Env,
    > {
        self.pending_ctor((target,), |env, id, _| {
            sails_rs::client::Actor::new(env, id)
        })
    }
    #[allow(clippy::type_complexity)]
    fn new_with_result(
        self,
        target: ActorId,
    ) -> sails_rs::client::PendingCtor<
        Result<sails_rs::client::Actor<InspectorClientProgram, Self::Env>, String>,
        io::NewWithResult,
        Self::Env,
    > {
        self.pending_ctor(
            (target,),
            |env, id, res: <io::NewWithResult as sails_rs::client::ServiceCall>::Reply| {
                res.map(|_| sails_rs::client::Actor::new(env, id))
            },
        )
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (target: ActorId) -> (), 0);
    sails_rs::io_struct_impl!(NewWithResult (target: ActorId) -> (), 1, throws String);
}

pub mod inspector {
    use super::*;

    #[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo, ReflectHash)]
    #[codec(crate = sails_rs::scale_codec)]
    #[scale_info(crate = sails_rs::scale_info)]
    #[reflect_hash(crate = sails_rs)]
    pub enum ValidationError {
        TooSmall,
        TooBig,
    }

    pub trait Inspector {
        type Env: sails_rs::client::GearEnv;
        /// Proxy call to validator.validate_even(7)
        fn test_even_panic(&self) -> sails_rs::client::PendingCall<io::TestEvenPanic, Self::Env>;
        /// Try to deploy demo with error - should return Err
        fn test_failing_demo_ctor(
            &self,
            demo_code_id: CodeId,
        ) -> sails_rs::client::PendingCall<io::TestFailingDemoCtor, Self::Env>;
        /// Proxy call to validator.validate_nonzero(0)
        fn test_nonzero_panic(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::TestNonzeroPanic, Self::Env>;
        /// Proxy call to validator.validate_range(20, 5, 15)
        fn test_range_panic(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::TestRangePanic, Self::Env>;
        /// Proxy call to validator.total_errors()
        fn test_total_errors(
            &self,
        ) -> sails_rs::client::PendingCall<io::TestTotalErrors, Self::Env>;
    }

    pub struct InspectorImpl;

    impl sails_rs::client::Identifiable for InspectorImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([223, 121, 120, 228, 241, 209, 29, 221]);
    }

    impl<E: sails_rs::client::GearEnv> Inspector for sails_rs::client::Service<InspectorImpl, E> {
        type Env = E;
        fn test_even_panic(&self) -> sails_rs::client::PendingCall<io::TestEvenPanic, Self::Env> {
            self.pending_call(())
        }
        fn test_failing_demo_ctor(
            &self,
            demo_code_id: CodeId,
        ) -> sails_rs::client::PendingCall<io::TestFailingDemoCtor, Self::Env> {
            self.pending_call((demo_code_id,))
        }
        fn test_nonzero_panic(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::TestNonzeroPanic, Self::Env> {
            self.pending_call(())
        }
        fn test_range_panic(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::TestRangePanic, Self::Env> {
            self.pending_call(())
        }
        fn test_total_errors(
            &self,
        ) -> sails_rs::client::PendingCall<io::TestTotalErrors, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(TestEvenPanic () -> u32, 0, <super::InspectorImpl as sails_rs::client::Identifiable>::INTERFACE_ID, throws ());
        sails_rs::io_struct_impl!(TestFailingDemoCtor (demo_code_id: CodeId) -> ActorId, 1, <super::InspectorImpl as sails_rs::client::Identifiable>::INTERFACE_ID, throws String);
        sails_rs::io_struct_impl!(TestNonzeroPanic () -> (), 2, <super::InspectorImpl as sails_rs::client::Identifiable>::INTERFACE_ID, throws String);
        sails_rs::io_struct_impl!(TestRangePanic () -> u32, 3, <super::InspectorImpl as sails_rs::client::Identifiable>::INTERFACE_ID, throws super::ValidationError);
        sails_rs::io_struct_impl!(TestTotalErrors () -> u32, 4, <super::InspectorImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }
}
