[package]
name = "sails-sender"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gstd.workspace = true
parity-scale-codec = { workspace = true, features = ["derive"] }
