program RmrkResource {
    constructors {
        New();
    }
    services {
        RmrkResource,
    }
    types {
        enum Error {
            NotAuthorized,
            ZeroResourceId,
            ResourceAlreadyExists,
            ResourceNotFound,
            WrongResourceType,
            PartNotFound,
        }

        enum Resource {
            Basic(BasicResource),
            Slot(SlotResource),
            Composed(ComposedResource),
        }

        struct BasicResource {
            /// URI like IPFS hash
            src: string,
            /// If the resource has the thumb property, this will be a URI to a thumbnail of the given
            /// resource.
            thumb: Option<string>,
            /// Reference to IPFS location of metadata
            metadata_uri: string,
        }

        struct SlotResource {
            /// URI like ipfs hash
            src: string,
            /// If the resource has the thumb property, this will be a URI to a thumbnail of the given
            /// resource.
            thumb: string,
            /// Reference to IPFS location of metadata
            metadata_uri: string,
            base: ActorId,
            /// If the resource has the slot property, it was designed to fit into a specific Base's slot.
            slot: u32,
        }

        struct ComposedResource {
            /// URI like ipfs hash
            src: string,
            /// If the resource has the thumb property, this will be a URI to a thumbnail of the given
            /// resource.
            thumb: string,
            /// Reference to IPFS location of metadata
            metadata_uri: string,
            base: ActorId,
            parts: [u32],
        }
    }
}

service RmrkResource {
    functions {
        AddPartToResource(resource_id: u8, part_id: u32) -> Result<u32, Error>;
        AddResourceEntry(resource_id: u8, resource: Resource) -> Result<(u8, Resource), Error>;
        @query
        Resource(resource_id: u8) -> Result<Resource, Error>;
    }
    events {
        ResourceAdded(resource_id: u8),
        PartAdded(resource_id: u8, part_id: u32),
    }
}