type Error = enum {
  NotAuthorized,
  ZeroResourceId,
  ResourceAlreadyExists,
  ResourceNotFound,
  WrongResourceType,
  PartNotFound,
};

type Resource = enum {
  Basic: BasicResource,
  Slot: SlotResource,
  Composed: ComposedResource,
};

type BasicResource = struct {
  /// URI like IPFS hash
  src: str,
  /// If the resource has the thumb property, this will be a URI to a thumbnail of the given
  /// resource.
  thumb: opt str,
  /// Reference to IPFS location of metadata
  metadata_uri: str,
};

type SlotResource = struct {
  /// URI like ipfs hash
  src: str,
  /// If the resource has the thumb property, this will be a URI to a thumbnail of the given
  /// resource.
  thumb: str,
  /// Reference to IPFS location of metadata
  metadata_uri: str,
  base: actor_id,
  /// If the resource has the slot property, it was designed to fit into a specific Base's slot.
  slot: u32,
};

type ComposedResource = struct {
  /// URI like ipfs hash
  src: str,
  /// If the resource has the thumb property, this will be a URI to a thumbnail of the given
  /// resource.
  thumb: str,
  /// Reference to IPFS location of metadata
  metadata_uri: str,
  base: actor_id,
  parts: vec u32,
};

constructor {
  New : ();
};

service RmrkResource {
  /// !@interface_id = 0x9730cce8a925be37
  /// !@entry_id = 0x0001
  AddPartToResource : (resource_id: u8, part_id: u32) -> result (u32, Error);
  /// !@entry_id = 0x0002
  AddResourceEntry : (resource_id: u8, resource: Resource) -> result (struct { u8, Resource }, Error);
  /// !@entry_id = 0x0003
  query Resource : (resource_id: u8) -> result (Resource, Error);

  events {
    /// !@entry_id = 0x0002
    ResourceAdded: struct {
      resource_id: u8
    };
    /// !@entry_id = 0x0001
    PartAdded: struct {
      resource_id: u8,
      part_id: u32,
    };
  }
};

