[package]
name = "fibo-bench-sails-app-plain"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gstd.workspace = true
parity-scale-codec.workspace = true

[dev-dependencies]
gtest.workspace = true

[build-dependencies]
gwasm-builder.workspace = true

[features]
std = []
default = ["std"]