[package]
name = "benchmarks"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
serde = { workspace = true, features = ["derive"] }
serde-json.workspace = true
fs2.workspace = true

[dev-dependencies]
gtest.workspace = true
sails-rs = { workspace = true, features = ["gtest"] }
alloc-stress-app = { path = "alloc-stress/app" }
alloc-stress-client = { path = "alloc-stress/client" }
compute-stress-app = { path = "compute-stress/app" }
compute-stress-client = { path = "compute-stress/client" }
counter-bench-app = { path = "counter-bench/app" }
counter-bench-client = { path = "counter-bench/client" }
ping-pong-bench-app = { path = "ping-pong/app" }
tokio = { workspace = true, features = ["rt", "macros"] }
tempfile.workspace = true
