[package]
name = "counter-bench-client"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sails-rs.workspace = true

[build-dependencies]
counter-bench-app = { path = "../app" }
sails-client-gen.workspace = true
sails-idl-gen.workspace = true
