type ThisThatSvcAppTupleStruct = struct {
  bool,
};

type ThisThatSvcAppDoThatParam = struct {
  p1: u32,
  p2: str,
  p3: ThisThatSvcAppManyVariants,
};

type ThisThatSvcAppManyVariants = enum {
  One,
  Two: u32,
  Three: opt u32,
  Four: struct { a: u32, b: opt u16 },
  Five: struct { str, u32 },
  Six: struct { u32 },
};

type SimpleStruct = struct {
  a: result (str, u32),
  b: u32,
};

type SimpleEnum = enum {
  One,
  Two,
  Three,
};

service {
  DoThis : (p1: u32, p2: str, p3: struct { opt str, u8 }, p4: ThisThatSvcAppTupleStruct) -> struct { str, u32 };
  DoThat : (param: ThisThatSvcAppDoThatParam) -> result (struct { str, u32 }, struct { str });
  query This : () -> u32;
  query That : () -> result (str, str);
}
