// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct PartialIdlClientProgram;

impl PartialIdlClientProgram {
    pub const ROUTE_ID_PARTIAL_IDL_SERVICE: u8 = 1;
}

impl sails_rs::client::Program for PartialIdlClientProgram {}

pub trait PartialIdlClient {
    type Env: sails_rs::client::GearEnv;
    fn partial_idl_service(
        &self,
    ) -> sails_rs::client::Service<partial_idl_service::PartialIdlServiceImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> PartialIdlClient
    for sails_rs::client::Actor<PartialIdlClientProgram, E>
{
    type Env = E;
    fn partial_idl_service(
        &self,
    ) -> sails_rs::client::Service<partial_idl_service::PartialIdlServiceImpl, Self::Env> {
        self.service(PartialIdlClientProgram::ROUTE_ID_PARTIAL_IDL_SERVICE)
    }
}
pub trait PartialIdlClientCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(self) -> sails_rs::client::PendingCtor<PartialIdlClientProgram, io::New, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> PartialIdlClientCtors
    for sails_rs::client::Deployment<PartialIdlClientProgram, E>
{
    type Env = E;
    fn new(self) -> sails_rs::client::PendingCtor<PartialIdlClientProgram, io::New, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New () -> (), 0);
}

pub mod partial_idl_service {
    use super::*;

    pub trait PartialIdlService {
        type Env: sails_rs::client::GearEnv;
        fn second(&mut self, val: u32) -> sails_rs::client::PendingCall<io::Second, Self::Env>;
        fn third(&mut self) -> sails_rs::client::PendingCall<io::Third, Self::Env>;
    }

    pub struct PartialIdlServiceImpl;

    impl sails_rs::client::Identifiable for PartialIdlServiceImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([111, 150, 73, 73, 94, 4, 30, 188]);
    }

    impl<E: sails_rs::client::GearEnv> PartialIdlService
        for sails_rs::client::Service<PartialIdlServiceImpl, E>
    {
        type Env = E;
        fn second(&mut self, val: u32) -> sails_rs::client::PendingCall<io::Second, Self::Env> {
            self.pending_call((val,))
        }
        fn third(&mut self) -> sails_rs::client::PendingCall<io::Third, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Second (val: u32) -> u32, 1, <super::PartialIdlServiceImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Third () -> String, 2, <super::PartialIdlServiceImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode, ReflectHash)]
        #[codec(crate = sails_rs::scale_codec)]
        #[reflect_hash(crate = sails_rs)]
        pub enum PartialIdlServiceEvents {
            #[codec(index = 2)]
            ThirdDone(String),
        }

        impl PartialIdlServiceEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::ThirdDone { .. } => 2,
                }
            }
        }

        impl sails_rs::client::Event for PartialIdlServiceEvents {}

        impl sails_rs::client::Identifiable for PartialIdlServiceEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <PartialIdlServiceImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for PartialIdlServiceImpl {
            type Event = PartialIdlServiceEvents;
        }
    }
}
