name: '[rs] Benchmarks'

on:
  pull_request:
    # types: [labeled]
    # paths:
    #   - 'rs/**'
    #   - 'Cargo.lock'
    #   - 'Cargo.toml'
  push:
    branches: [master]
    paths:
      - 'rs/**'
      - 'Cargo.lock'
      - 'Cargo.toml'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  benchmark:
    # if: contains(github.event.label.name, 'run-benchmarks')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      # Checkout the current branch (PR branch)
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Free Disk Space
        uses: ./.github/actions/free-disk-space

      - name: Install wasm-opt
        uses: ./.github/actions/install-wasm-utils

      # Run benchmarks on PR branch
      - name: Run Benchmarks
        run: |
          make bench

      # todo [sab] check if you can download only one file
      # Checkout master branch to get baseline JSON
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master
          path: master-branch

      # Copy baseline JSON from master
      - name: Copy Baseline JSON
        run: |
          cp master-branch/benchmarks/bench_data.json baseline.json

      # Update the bench files formats
      - name: Convert PR Bench Data
        run: |
          cargo run --bin convert-bench-data --manifest-path=benchmarks/Cargo.toml -- benchmarks/bench_data.json bench_data_pr_converted.json

      - name: Convert Baseline Bench Data
        run: |
          cargo run --bin convert-bench-data --manifest-path=benchmarks/Cargo.toml -- baseline.json bench_data_baseline_converted.json

      - name: Display Bench Data
        run: |
          echo "PR Bench Data:"
          cat bench_data_pr_converted.json
          echo "Baseline Bench Data:"
          cat bench_data_baseline_converted.json

      # Compare benchmarks using github-action-benchmark
      - name: Compare Benchmarks
        uses: benchmark-action/github-action-benchmark@v1.20.4
        with:
          tool: 'customSmallerIsBetter'
          benchmark-data-dir-path: .
          output-file-path: bench_data_pr_converted.json
          external-data-json-path: bench_data_baseline_converted.json
          comment-always: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-alert: true
          save-data-file: false
          ref: ${{ github.event.pull_request.head.sha }}
          alert-threshold: "1%"