name: CI (.Net)

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ci-net.yml'
      - 'net/**'
      - 'Sales.Net.sln'

  pull_request:
    paths:
      - '.github/workflows/ci-net.yml'
      - 'net/**'
      - 'Sales.Net.sln'

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check Out Source
        uses: actions/checkout@v4

      - name: Set Up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore Solution
        run: >-
          dotnet restore

      - name: Build Solution
        run: >-
          dotnet build --no-restore
