name: '[net] Build client-gen-dotnet'

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/net-build-client-gen.yml'
      - 'rs/**'

  pull_request:
    paths:
      - '.github/workflows/net-build-client-gen.yml'
      - 'rs/**'

jobs:
  win-x64:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - run: cargo build -p sails-client-gen-dotnet --release
      - uses: actions/upload-artifact@v4
        with:
          name: win-x64
          path: ./target/release/sails_client_gen_dotnet.dll
          retention-days: 1

  linux-x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo build -p sails-client-gen-dotnet --release
      - uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: ./target/release/libsails_client_gen_dotnet.so
          retention-days: 1
  
  osx-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo build -p sails-client-gen-dotnet --release
      - uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: ./target/release/libsails_client_gen_dotnet.dylib
          retention-days: 1
