name: '[rs] Benchmarks'

on:
  pull_request:
    # types: [labeled]
    # paths:
    #   - 'rs/**'
    #   - 'Cargo.lock'
    #   - 'Cargo.toml'
  push:
    branches: [master]
    paths:
      - 'rs/**'
      - 'Cargo.lock'
      - 'Cargo.toml'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  benchmark:
    # if: contains(github.event.label.name, 'run-benchmarks')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      # Checkout the current branch (PR branch)
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Free Disk Space
        uses: ./.github/actions/free-disk-space

      - name: Install wasm-opt
        uses: ./.github/actions/install-wasm-utils

      # Run benchmarks on PR branch
      - name: Run Benchmarks
        run: |
          make bench

      # todo [sab] check if you can download only one file
      # Checkout master branch to get baseline JSON
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master
          path: master-branch

      # Copy baseline JSON from master
      - name: Copy Baseline JSON
        run: |
          cp master-branch/benchmarks/bench_data.json baseline.json

      - name: Display Bench Data
        run: |
          echo "PR Bench Data:"
          cat benchmarks/bench_data.json
          echo "Baseline Bench Data:"
          cat baseline.json
