name: '[rs] Run Workspace Tests'

on:
  workflow_call:
    inputs:
      sources_ref:
        description: 'Sources Ref'
        type: string
        required: false
      gear_node_version:
        description: 'Gear Node Version'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  test_ws:
    name: Run Workspace Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sources_ref }}

      - name: Free Disk Space
        uses: ./.github/actions/free-disk-space

      - name: Install wasm-opt
        uses: ./.github/actions/install-wasm-utils

      - name: Download Gear Node
        run: |
          sudo wget -O ./gear https://github.com/gear-tech/gear/releases/download/v${{ inputs.gear_node_version }}/gear
          sudo chmod +x gear
          sudo mv gear /usr/bin/

      - name: Run Tests
        env:
          GEAR_PATH: /usr/bin/gear
        run: __GEAR_WASM_BUILDER_NO_FEATURES_TRACKING=1 cargo test --workspace --all-targets --locked --no-fail-fast -- --include-ignored

      - name: Run Tests in Ethexe Workspace
        env:
          GEAR_PATH: /usr/bin/gear
        run: __GEAR_WASM_BUILDER_NO_FEATURES_TRACKING=1 cargo test --workspace --all-targets --locked --no-fail-fast --manifest-path ./rs/ethexe/Cargo.toml
