name: '[rs] Run CLI Tests'

on:
  workflow_call:
    inputs:
      sources_ref:
        description: 'Sources Ref'
        type: string
        required: false

env:
  CARGO_TERM_COLOR: always

jobs:
  test_cli:
    name: Run CLI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sources_ref }}

      - name: Free Disk Space
        uses: ./.github/actions/free-disk-space

      - name: Install wasm-opt
        uses: ./.github/actions/install-wasm-utils

      - name: Build CLI
        run: |
          cargo build -p sails-cli

      - name: Generate MyDemo via CLI
        run: |
          ./target/debug/cargo-sails sails new ~/tmp/my-demo --name my-demo --sails-path ./rs

      - name: Run Tests on MyDemo
        run: |
          cargo test --workspace --manifest-path ~/tmp/my-demo/Cargo.toml

      - name: Generate IDL from MyDemo via CLI
        run: |
          ./target/debug/cargo-sails sails idl --manifest-path ~/tmp/my-demo/Cargo.toml
          diff ~/tmp/my-demo/target/my-demo-app.idl ~/tmp/my-demo/client/my_demo_client.idl
