// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::collections::BTreeMap;
#[allow(unused_imports)]
use sails_rs::{
    calls::{Activation, Call, Query, Remoting, RemotingAction},
    prelude::*,
    String,
};
pub struct PlainFactory<R> {
    #[allow(dead_code)]
    remoting: R,
}
impl<R> PlainFactory<R> {
    #[allow(unused)]
    pub fn new(remoting: R) -> Self {
        Self { remoting }
    }
}
impl<R: Remoting + Clone> traits::PlainFactory for PlainFactory<R> {
    type Args = R::Args;
    fn new(&self) -> impl Activation<Args = R::Args> {
        RemotingAction::<_, plain_factory::io::New>::new(self.remoting.clone(), ())
    }
}

pub mod plain_factory {
    use super::*;
    pub mod io {
        use super::*;
        use sails_rs::calls::ActionIo;
        pub struct New(());
        impl New {
            #[allow(dead_code)]
            pub fn encode_call() -> Vec<u8> {
                <New as ActionIo>::encode_call(&())
            }
        }
        impl ActionIo for New {
            const ROUTE: &'static [u8] = &[12, 78, 101, 119];
            type Params = ();
            type Reply = ();
        }
    }
}
pub struct AsyncService<R> {
    remoting: R,
}
impl<R> AsyncService<R> {
    pub fn new(remoting: R) -> Self {
        Self { remoting }
    }
}
impl<R: Remoting + Clone> traits::AsyncService for AsyncService<R> {
    type Args = R::Args;
    fn some_async_method(&mut self) -> impl Call<Output = String, Args = R::Args> {
        RemotingAction::<_, async_service::io::SomeAsyncMethod>::new(self.remoting.clone(), ())
    }
}

pub mod async_service {
    use super::*;

    pub mod io {
        use super::*;
        use sails_rs::calls::ActionIo;
        pub struct SomeAsyncMethod(());
        impl SomeAsyncMethod {
            #[allow(dead_code)]
            pub fn encode_call() -> Vec<u8> {
                <SomeAsyncMethod as ActionIo>::encode_call(&())
            }
        }
        impl ActionIo for SomeAsyncMethod {
            const ROUTE: &'static [u8] = &[
                48, 65, 115, 121, 110, 99, 83, 101, 114, 118, 105, 99, 101, 60, 83, 111, 109, 101,
                65, 115, 121, 110, 99, 77, 101, 116, 104, 111, 100,
            ];
            type Params = ();
            type Reply = String;
        }
    }
}
pub struct NoAsyncService<R> {
    remoting: R,
}
impl<R> NoAsyncService<R> {
    pub fn new(remoting: R) -> Self {
        Self { remoting }
    }
}
impl<R: Remoting + Clone> traits::NoAsyncService for NoAsyncService<R> {
    type Args = R::Args;
    fn some_method(&self) -> impl Query<Output = String, Args = R::Args> {
        RemotingAction::<_, no_async_service::io::SomeMethod>::new(self.remoting.clone(), ())
    }
}

pub mod no_async_service {
    use super::*;

    pub mod io {
        use super::*;
        use sails_rs::calls::ActionIo;
        pub struct SomeMethod(());
        impl SomeMethod {
            #[allow(dead_code)]
            pub fn encode_call() -> Vec<u8> {
                <SomeMethod as ActionIo>::encode_call(&())
            }
        }
        impl ActionIo for SomeMethod {
            const ROUTE: &'static [u8] = &[
                56, 78, 111, 65, 115, 121, 110, 99, 83, 101, 114, 118, 105, 99, 101, 40, 83, 111,
                109, 101, 77, 101, 116, 104, 111, 100,
            ];
            type Params = ();
            type Reply = String;
        }
    }
}

pub mod traits {
    use super::*;
    #[allow(dead_code)]
    pub trait PlainFactory {
        type Args;
        #[allow(clippy::new_ret_no_self)]
        #[allow(clippy::wrong_self_convention)]
        fn new(&self) -> impl Activation<Args = Self::Args>;
    }

    #[allow(clippy::type_complexity)]
    pub trait AsyncService {
        type Args;
        fn some_async_method(&mut self) -> impl Call<Output = String, Args = Self::Args>;
    }

    #[allow(clippy::type_complexity)]
    pub trait NoAsyncService {
        type Args;
        fn some_method(&self) -> impl Query<Output = String, Args = Self::Args>;
    }
}
