// Code generated by sails-client-gen. DO NOT EDIT.
use sails_rs::{client::*, prelude::*};
pub struct NoSvcsProgProgram;
impl Program for NoSvcsProgProgram {}
pub trait NoSvcsProg {
    type Env: GearEnv;
}
impl<E: GearEnv> NoSvcsProg for Actor<E, NoSvcsProgProgram> {
    type Env = E;
}
pub trait NoSvcsProgCtors {
    type Env: GearEnv;
    fn create(self) -> PendingCtor<Self::Env, NoSvcsProgProgram, io::Create>;
}
impl<E: GearEnv> NoSvcsProgCtors for Deployment<E, NoSvcsProgProgram> {
    type Env = E;
    fn create(self) -> PendingCtor<Self::Env, NoSvcsProgProgram, io::Create> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> ());
}
